### ISSUE TITLE
请问 atlas-generator 是哪个三方工具?

### ISSUE THREAD

**Issue by cupen** [a7359475/layaair-cmd#6]
我在折腾 linux 下运行 `layaair-cmd` 的办法.

**Comment by WebRelDesigner** [comment]
atlas-generator 好像是Laya自主研发的

**Comment by WebRelDesigner** [comment]
论坛上好像有源码提供
https://ask.layabox.com/question/48079

**Comment by cupen** [comment]
> 论坛上好像有源码提供 https://ask.layabox.com/question/48079

哦，谢谢。我下载到源码了。
压缩包是个 git 仓库。原地址是  https://gitlab.com/hyzmm/atlas-generator
敢情早就开源了……  


谢谢大家。
